In [19]:
%matplotlib notebook
import os
import math
import numpy as np
import qutip as qt
import scipy
from scipy import constants
from scipy import interpolate
from scipy import integrate
import sympy as sym
from systemConst import ket,iniState1Qsys,iniState2Qsys,Tunabletransmon,QQ
#from CZwave import CZpulse

import matplotlib.pyplot as plt
import sys
import quantum_okiba as qo
from tqdm import tqdm
from qiskit import QuantumCircuit,visualization,Aer,execute
from qiskit.quantum_info import average_gate_fidelity

In [20]:
pi = np.pi
e = constants.e # [C]
h = constants.h # [m^2 kg/s]
hbar = constants.hbar
iDir = 'C:/Users/Sota/Scripts/TestKankyo/cQEDSim/core'
opts = qt.solver.Options(nsteps=10000)

In [21]:
#回路を設計
circ = QuantumCircuit(2)
#circ.x(0)
#circ.x(1)
circ.z(1)
circ.draw()

q_0: ─────
     ┌───┐
q_1: ┤ Z ├
     └───┘

In [22]:
#回路を実行1
backend = Aer.get_backend('statevector_simulator')
job = execute(circ, backend) #これでstatusとresultを得られる状態に

result = job.result()
outputstate = result.get_statevector(circ, decimals=3)
qp=qt.Qobj(outputstate)
qp

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [23]:
backend = Aer.get_backend('unitary_simulator')
job = execute(circ, backend) #これでstatusとresultを得られる状態に

result = job.result()
cz=qt.Qobj(result.get_unitary(circ, decimals=3))
cz

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]

In [24]:
sp = qt.sigmap()
sm = qt.sigmam()

In [25]:
I2=qt.qeye(2)
sI2=qt.operator_to_vector(I2)
sI3=qt.vector_to_operator(sI2)

In [26]:
from Matrice import evals,paulis_set,_tr,pY_N,pI_N,pX_N,pZ_N

I=pI_N(3)
#x=qt.sigmax()
x=pX_N(3)
#y=qt.sigmay()
y=pY_N(3)
#z=qt.sigmaz()
z=pZ_N(3)

paulis=paulis_set(3)

In [27]:
r1=iniState1Qsys(2,1,mode='rho')
print(r1)
r2=qt.tensor(qt.qeye(2),qt.qeye(2))
r3=qt.tensor(r1,r1)
print(r2-2*r3)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]]
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]
